# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alsaeed <alsaeed@student.42abudhabi.ae>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/11 14:48:47 by alsaeed           #+#    #+#              #
#    Updated: 2024/01/06 03:52:53 by alsaeed          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

$(NAME): all

all: 
	@make all -sC src
	
clean:
	@make clean -sC src

fclean: clean
	@make fclean -sC src

re: fclean all